### ISSUE TITLE
The CLI won't let me add a license

### ISSUE THREAD

**Issue by coffeeboo** [licensezero/cli#17]
```
 jasonidris@coffeeboo ⮀ ~/go/src/memefactory ⮀ ⭠ master ✚ ⮀ licensezero license --prosperity <insert project id>
Write LICENSE and package metadata for your project.

Usage:
  licensezero license --project ID (--parity | --prosperity) [--stack]

Options:
  --parity      Use The Parity Publice License.
  --project     Project ID (UUID).
  --prosperity  Use the Prosperity Public License.
  --silent      Suppress output about success.
  --stack       Stack multiple project metadata entries.

✘ jasonidris@coffeeboo ⮀ ~/go/src/memefactory ⮀ ⭠ master ✚ ⮀
```

This is the format that was on the site. Am I doing something wrong?

**Comment by kemitchell** [comment]
Instead of:

```bash
licensezero license --prosperity <insert project id>
```

Try:

```bash
licensezero license --prosperity --project <insert project id>
```

**Comment by coffeeboo** [comment]
Never mind.

```
echo "{}" >> package.json
licensezero license --prosperity --project <insert project id>
```

But I would appreciate it if I didn't have to do this.

**Comment by kemitchell** [comment]
@coffeeboo are you using the current Go CLI? `licensezero version` should print `v4.2.1`. The current version will write `licensezero.json`, not `package.json`.

The CLI already offers basic Go support, for dependencies that others install in their working trees, such as in `vendor`. It doesn't yet support imports _outside_ the project working tree, such as those installed in `$GOPATH`.

I have a few notes on that in #10. If you have insight into how best to find and recurse Go dependencies, I'd love your input there!

**Comment by coffeeboo** [comment]
3.0.2. I upgraded to latest.
