### ISSUE TITLE
Project badge should not be cached

### ISSUE THREAD

**Issue by joehand** [licensezero/cli#21]
I repriced a project via CLI and updated the readme, https://github.com/neat-log/neat-log. Unfortunately, it looks like Github is caching the old badge. The badge is correct on the license zero site: https://licensezero.com/ids/0153a099-6acd-4023-8a96-9d81d9969a58/badge.svg.

It looks like other badge providers set `Cache-Control: no-cache` for badges to avoid this.

**Comment by kemitchell** [comment]
@joehand This is excellent feedback. I'm going to fix it now.

Since you may be interested: I plan to release the server source code shortly, under Parity, without any private licensing options.

**Comment by kemitchell** [comment]
This is really something I should have thought of! https://www.npmjs.com/package/do-not-cache

**Comment by kemitchell** [comment]
```
$ curl -sSL -D - https://licensezero.com/ids/6d3f67d4-af32-4959-abe3-dacd765484f3/badge.svg -o /dev/null
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Thu, 05 Jul 2018 17:13:00 GMT
Content-Type: image/svg+xml
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=15768000
```
