### ISSUE TITLE
Error sending license information request: invalid body

### ISSUE THREAD

**Issue by joehand** [licensezero/cli#26]
Getting an invalid body error when I try to do things:

```
 licensezero offer --price 300 --no-relicense --homepage github.com/joehand/dat-download --description "Simple utility to download dats"
Error sending offer request: invalid body
```

or:

```
❯ licensezero license --id jhand-dat-download --prosperity
Error sending license information request: invalid body
```

Just re-installed, haven't used for a bit on this computer but looks like my identity is still there:

```
❯ licensezero version
6.1.1
❯ licensezero whoami
Name: Joe Hand
Jurisdiction: US-OR
E-Mail: joe@hand.email
Licensor ID: my-id
```

**Comment by kemitchell** [comment]
Thanks, @joehand. On this now.

**Comment by kemitchell** [comment]
@joehand the value of `--id` should be the UUID that licensezero.com assigns when you run `licensezero offer`.

**Comment by kemitchell** [comment]
Also: The CLI should warn if the `--id` value isn't a UUID. Right now it doesn't. Could've saved you some head scratching.

**Comment by joehand** [comment]
Ah thanks @kemitchell, answers one of my questions.

However, I got the same error trying to do the offer. Do I have one of these options wrong too? 

```
 licensezero offer --price 300 --no-relicense --homepage github.com/joehand/dat-download --description "Simple utility to download dats"
```

**Comment by kemitchell** [comment]
Back to you soon!

**Comment by kemitchell** [comment]
@joehand try it with a complete URL?

```bash
 licensezero offer \
--price 300 \
--no-relicense \
--homepage https://github.com/joehand/dat-download \
--description "simple utility to download dats"
```

If you get output, cloud you share it?

**Comment by joehand** [comment]
Great, worked! https://licensezero.com/ids/67986d53-c480-4633-8cdf-e4d0d9ae61c6

Was definitely doing then when a missing `http` would have been the last thing I noticed!

**Comment by kemitchell** [comment]
@joehand you had a terrible experience with this, and that was the CLI's fault, not yours. I am back in the Go codebase looking at what I can do to validate more command-line inputs on the client side.
