### ISSUE TITLE
Error during register

### ISSUE THREAD

**Issue by ramiel** [licensezero/cli#28]
When I try to register I get the following error

```
$ licensezero register


Name: *** ***
Jurisdiction: IT-IT
E-Mail: ***@***.it
Is this information correct? (y/n): y
Do you agree to the terms of service at https://licensezero.com/terms/service? (y/n): y
Error sending register request: invalid body
```

Version 6.1.1

**Comment by kemitchell** [comment]
@ramiel where do you live in Italy? Your jurisdiction should be one of these: https://it.wikipedia.org/wiki/ISO_3166-2:IT

**Comment by kemitchell** [comment]
Note to Self: Really need to address #22.

**Comment by kemitchell** [comment]
@ramiel, thanks to motivation from you, v6.2.0 now validates `--jurisdiction` values on its own. I am also planning to create a single-page jurisdictions.licensezero.com explainer page to help guide people.

**Comment by ramiel** [comment]
Ok, thanks,it is indeed a problem with jurisdiction. Yes, a clear validation error would help. Thank you again

**Comment by ramiel** [comment]
Worked perfectly. I'm closing this

**Comment by kemitchell** [comment]
Excellent! And sorry you had trouble to begin with.

Just FYI, I should mention that the server code for licensezero.com is also open here on GitHub. Open issues and PRs anytime.
