### ISSUE TITLE
Help Wanted: Guidance on Rust/Cargo Dependency Detection

### ISSUE THREAD

**Issue by kemitchell** [licensezero/cli#32]
Currently, `licensezero quote` does nothing specific to detect crates for Rust projects. If a crate's directory appears within the current working directory at any level of depth and the crate's directory contains a `licensezero.json` file, it's detected and managed that way. But I understand that "vendoring" crate dependencies in that way is _not_ typical of Rust development.

@zkat, do you happen to know of a Cargo command or other way to get a list of all the dependencies of a Rust project in `$CWD`, along with their filesystem paths? Could we recurse the filesystem paths from there to find licensezero.json files?

**Comment by zkat** [comment]
There's nothing built into the Cargo CLI to do this. You'd have to write a little helper binary that invokes maaaybe something like [`cargo::ops::resolve_ws`](https://docs.rs/cargo/0.38.0/cargo/ops/fn.resolve_ws.html), though I'm not sure how to grab the local cache path from that.

**Comment by kemitchell** [comment]
@zkat thanks. I had a good look at `cargo help`, but didn't see anything. Thanks for confirming.

@ashleygwilliams, License Zero is welcoming lots of Rustsaceans! I think it's time for the License Zero to provide first-class support for Cargo/Crate dependencies. Might you be available to provide some guidance on how to go about...?:

1. finding paths for all dependencies of a Rust/Cargo project, given the working directory of the project

2. including a `licensezero.json` or other metadata payload in crates, so they can be read once the library paths are found

This is _not_ a request for free work. I'll be happy to both acknowledge and compensate. Feel free to e-mail me on that point if you prefer.

**Comment by ashleygwilliams** [comment]
hey @kemitchell ! i'd love to help! let's set up some time to chat!

**Comment by mgattozzi** [comment]
Related to support with cargo/crates.io I had opened up this issue:
https://github.com/rust-lang/crates.io/issues/1828

Turns out you can list license zero with the license-file key in `Cargo.toml`. Others that are more standard like MIT, MPL-2.0, etc. can be listed in the license field. You can grab all the metadata that you need via `cargo metadata` being run somewhere in the project directory. The output is JSON so it should be possible to invoke `cargo` and consume it's output in Go.

More info on the command itself and it's output:
https://doc.rust-lang.org/cargo/commands/cargo-metadata.html

**Comment by kemitchell** [comment]
@mgattozzi awesome! Just to be clear: Is `cargo-metadata` shipped with Cargo, so that everyone who has `cargo` also has `cargo metadata`?

I don't think we would rely entirely on the license. Some people use Parity or Prosperity _without_ selling private licenses via licensezero.com. But it sounds like we might be able to write additional properties to `Cargo.toml` and read them via `cargo metadata`.

**Comment by mgattozzi** [comment]
`cargo metadata` should exist on any machine that has it installed! As you can see here this subcommand is included in the official repo:

https://github.com/rust-lang/cargo/blob/master/src/bin/cargo/commands/metadata.rs

It's technically the `cargo-metadata` binary that is invoked (`cargo --help` won't show this as a subcommand) and all `cargo-*` prefixed binaries in one path can be invoked by `cargo` as a subcommand!

**Comment by kemitchell** [comment]
@mgattozzi Excellent!

I've just found `package.metadata` in `Cargo.toml`:

https://github.com/licensezero/license-zero-test-crate/blob/e68330385b9be856f918578057056420af8a9718/Cargo.toml#L11

**Comment by kemitchell** [comment]
@mgattozzi you cracked it!  Here's `cargo metadata --format-version 1 | json` with `license-zero-test-crate` as a dependency:

```
{
  "packages": [
    {
      "name": "test-bom",
      "version": "0.1.0",
      "id": "test-bom 0.1.0 (path+file:///home/kyle/test-bom)",
      "license": null,
      "license_file": null,
      "description": null,
      "source": null,
      "dependencies": [
        {
          "name": "license-zero-test-crate",
          "source": "registry+https://github.com/rust-lang/crates.io-index",
          "req": "^0.1.0",
          "kind": null,
          "rename": null,
          "optional": false,
          "uses_default_features": true,
          "features": [],
          "target": null,
          "registry": null
        }
      ],
      "targets": [
        {
          "kind": [
            "bin"
          ],
          "crate_types": [
            "bin"
          ],
          "name": "test-bom",
          "src_path": "/home/kyle/test-bom/src/main.rs",
          "edition": "2018"
        }
      ],
      "features": {},
      "manifest_path": "/home/kyle/test-bom/Cargo.toml",
      "metadata": null,
      "authors": [
        "Kyle E. Mitchell <kyle@kemitchell.com>"
      ],
      "categories": [],
      "keywords": [],
      "readme": null,
      "repository": null,
      "edition": "2018",
      "links": null
    },
    {
      "name": "license-zero-test-crate",
      "version": "0.1.0",
      "id": "license-zero-test-crate 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
      "license": null,
      "license_file": "LICENSE",
      "description": "licensezero.com test crate",
      "source": "registry+https://github.com/rust-lang/crates.io-index",
      "dependencies": [],
      "targets": [
        {
          "kind": [
            "bin"
          ],
          "crate_types": [
            "bin"
          ],
          "name": "license-zero-test-crate",
          "src_path": "/home/kyle/.cargo/registry/src/github.com-1ecc6299db9ec823/license-zero-test-crate-0.1.0/src/main.rs",
          "edition": "2018"
        }
      ],
      "features": {},
      "manifest_path": "/home/kyle/.cargo/registry/src/github.com-1ecc6299db9ec823/license-zero-test-crate-0.1.0/Cargo.toml",
      "metadata": {
        "licensezero": {
          "version": "1.0.0",
          "ids": [
            {
              "agentSignature": "99f940a4937204a51d86e95e3733bdc69ec3d16ad3b8aaf25d370da063fc90778e61e9886ac1ed7c5e65021889c8d891b96f0c5addd9d9b651ac5b1eb8b3ac01",
              "licensorSignature": "c475a1104409f8117e66be4dd09997d1e15ca8513d578edc7d80f6662434b13ebb55a0b7f4ecffbb9fa9be588ad3fd0630471ebb5fb7d7b77cc065e98d549502",
              "license": {
                "homepage": "https://github.com/licensezero/license-zero-test-crate",
                "jurisdiction": "US-CA",
                "name": "Kyle E. Mitchell",
                "projectID": "a72f8da3-429a-4bd5-8c2d-4242344b9cd3",
                "publicKey": "1589d5a1b9b6b6ca26515b65fe9f725410c9f7fa41bcd9954a84d76f47cc6482",
                "terms": "parity",
                "version": "6.0.0"
              }
            }
          ]
        }
      },
      "authors": [
        "Kyle E. Mitchell <kyle@kemitchell.com>"
      ],
      "categories": [],
      "keywords": [],
      "readme": null,
      "repository": null,
      "edition": "2018",
      "links": null
    }
  ],
  "workspace_members": [
    "test-bom 0.1.0 (path+file:///home/kyle/test-bom)"
  ],
  "resolve": {
    "nodes": [
      {
        "id": "license-zero-test-crate 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
        "dependencies": [],
        "deps": [],
        "features": []
      },
      {
        "id": "test-bom 0.1.0 (path+file:///home/kyle/test-bom)",
        "dependencies": [
          "license-zero-test-crate 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"
        ],
        "deps": [],
        "features": []
      }
    ],
    "root": "test-bom 0.1.0 (path+file:///home/kyle/test-bom)"
  },
  "target_directory": "/home/kyle/test-bom/target",
  "version": 1,
  "workspace_root": "/home/kyle/test-bom"
}
```

**Comment by kemitchell** [comment]
@ashleygwilliams, FYI, it looks like we've got it. `[package.metadata.licensezero]`, then `cargo metadata --format-version 1`.

**Comment by mgattozzi** [comment]
@kemitchell Glad this got you everything that you needed!

**Comment by mgattozzi** [comment]
Note that the `license` field in your `Cargo.toml` right now won't allow upload to crates.io the license should be a file in the repo and referenced with `license-file` so that uploading to crates.io works. You could put it's pull name in the metadata if you want as well 😄

**Comment by kemitchell** [comment]
@mgattozzi I figured out the `license` versus `license-file` thing. I've also opened a PR on the crate with the SPDX IDs to update so that `Parity-6.0.0` and `BlueOak-1.0.0` are supported.

**Comment by mgattozzi** [comment]
Ah awesome! 😄
