### ISSUE TITLE
Error sending offer request: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by SKalt** [licensezero/cli#36]

**Comment by kemitchell** [comment]
@SKalt can you give me more information on when you saw the error, such as the options you passed to `licensezero offer`?

**Comment by SKalt** [comment]
Oh, shoot! I meant to delete this issue, since the root cause was a typo.  I was submitting `my-gh-pages.gihub.io` rather than `my-gh-pages.github.io`.  `gihub.io` turns out to do spam and spam redirects. Correcting the typo resolved the problem.
