### ISSUE TITLE
Bug: Secret prompt crashes the licensezero command on windows.

### ISSUE THREAD

**Issue by royaltm** [licensezero/cli#37]
While trying to use licensezero-windows-amd64.exe on Windows 10 (64 bit):

```
C:\>licensezero token --licensor xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Token: panic: read stdin: Nieprawidłowe dojście.

goroutine 1 [running]:
licensezero.com/cli/subcommands.secretPrompt(0x87079d, 0x7, 0x2, 0x2)
        /home/travis/gopath/src/github.com/licensezero/cli/subcommands/prompts.go:30 +0x110
licensezero.com/cli/subcommands.glob..func19(0xc0000640e0, 0x2, 0x2, 0xc000066580, 0x1c, 0xc0000665c0, 0xe)
        /home/travis/gopath/src/github.com/licensezero/cli/subcommands/token.go:24 +0x17b
main.main()
        /home/travis/gopath/src/github.com/licensezero/cli/main.go:54 +0x23d
```

I've tried the standard windows CMD, powershell, msys and msys2. It fails every time. The licenesor code given is valid (censored in the example) I've quadruple checked it.

**Comment by royaltm** [comment]
```
licensezero version
6.3.0
```

**Comment by kemitchell** [comment]
@royaltm, thank you for this report! I am looking into it.

**Comment by kemitchell** [comment]
@royaltm, thank you for your patience! I believe I have squashed this bug in v6.3.1, which you can install just as you did v6.3.0. For your reference, here is the one-line install script:

```bash
curl -sL https://licensezero.com/install.sh | sh
```

I believe the bug had to do with the file descriptor that I passed to the cryptographic library used to read the prompt without echoing input.

**Comment by royaltm** [comment]
@kemitchell thanks, it's ok now!
