### ISSUE TITLE
help information for "latest" is misleading

### ISSUE THREAD

**Issue by royaltm** [licensezero/cli#38]
```
$ licensezero help

...
  latest    Show your identity information.
...
  whoami    Show your identity information.

$ licensezero latest
Running: v6.3.1
Latest:  v6.3.1
```

I think instead of "your identity" there should be "latest available version for an update" or something along those lines.

**Comment by kemitchell** [comment]
@royaltm, would you be alright with a short public thanks on https://licensezero.com/thanks?

**Comment by royaltm** [comment]
@kemitchell why not? Go ahead!

**Comment by kemitchell** [comment]
Great! What URL would you like me to link to?

**Comment by royaltm** [comment]
Please use my github profile: https://github.com/royaltm

**Comment by kemitchell** [comment]
056c239c6508b413f9836ac766d3cdccbd4eaf4c
