### ISSUE TITLE
bug: readme command can't find metadata in Cargo.toml

### ISSUE THREAD

**Issue by royaltm** [licensezero/cli#39]
Instead of parsing Cargo.toml the cli tries to access metadata from a default JSON file:

```
$ licensezero license --id xxxxxxxx --prosperity
Added metadata to Cargo.toml.
Appended terms to LICENSE.

$ licensezero  readme
open project/licensezero.json: Nie można odnaleźć określonego pliku. (which translates to: "can't find a specific file")

$ licensezero latest
Running: v7.0.1
Latest:  v7.0.1
```

**Comment by royaltm** [comment]
The license command has also butchered my Cargo.toml, but I guess there is no easy way to add metadata without rewriting the whole toml file.

**Comment by kemitchell** [comment]
The lack of `Cargo.toml` support in `licensezero readme` is a clear oversight. I'm working on it.

Unfortunately, formatting of TOML files varies a bit. Maybe you know TOML better than I do: Would it be possible to formulate a string of TOML that we could just append to `Cargo.toml` in order to add the relevant metadata?

**Comment by royaltm** [comment]
Yes. To add a section: `[package.metadata.licensezero]` you don't need to add its ancestors:
```
[package]
[package.metadata]
```
It's enough that you just add the section you need. So e.g. you can append the following sections:
```
[package.metadata.licensezero]
  ...
[[package.metadata.licensezero.ids]]
  ...
[package.metadata.licensezero.ids.license]
  ...
```
to the toml file, perhaps parsing it previously in order to check if the section doesn't already exist. The check won't be atomic though, but I don't think it's important in this instance.

It's also unusual to intend sections, as licensezero is currently doing.

**Comment by kemitchell** [comment]
That append tip is great, but I’m not sure we can rely on it. The CLI may need to alter metadata in more ways than just appending entries, especially as schemas change.

I am going to look into whether I might improve the TOML serialization to look more idiomatic.

**Comment by royaltm** [comment]
Great! 7.0.2: readme command now reads tomls.
However if you'll work on this feature again, please check the output the command produces, cause it's currently debug printing the parsed toml section's content. I don't know if you left it on purpose or not, but looks slightly odd.

**Comment by kemitchell** [comment]
I left a debug statement in. One sec.

**Comment by kemitchell** [comment]
Fix is going out as 7.0.3.

**Comment by royaltm** [comment]
purrrrfect!

**Comment by kemitchell** [comment]
@royaltm Thanks again!

Cargo support is very new in the CLI. I've done a little Rust development myself, but not enough to really put the CLI through its paces. I _really_ appreciate how helpful you've been as "early adopter" of Cargo support!
