### ISSUE TITLE
OS Packaging

### ISSUE THREAD

**Issue by nyarly** [licensezero/cli#42]
I'm leery of curl-pipe-sh installs of software, and dubious about whether licensezero will work on my preferred platform (NixOS). Since it's a Go program, it'd be easy to provide build-from-source instruction which would further enable packaging processes.

**Comment by kemitchell** [comment]
`make`, or, for the new version coming up, `go build`.

**Comment by nyarly** [comment]
For my personal Nix setup, I put together https://github.com/nyarly/nix-config/blob/master/home/packages/licensezero/default.nix

The NPM requirements make it a little wonky, but not terrible. If you've no objection, I'll see about adding them to the main Nix tree.

**Comment by kemitchell** [comment]
Glad you found something that works.
